#short reads only

rule all:
	input:
		"output_dir/quast_results/transposed_report.tsv"	

#unicycler component
rule uni_start:
	input:
		r1="sample_data/short_reads_1.fastq.gz",
		r2="sample_data/short_reads_2.fastq.gz"
	output:
		"output_dir/assembly.gfa",
		"output_dir/assembly.fasta",
		"output_dir/unicycler.log"
	threads: 8
	shell:
		"unicycler -1 {input.r1} -2 {input.r2} -o output_dir -t 8"

#quast
rule run_quast:
	input:
		r1="output_dir/assembly.fasta"
	output:
		"output_dir/quast_results/transposed_report.tsv"
	shell:
		"quast.py {input.r1} -o output_dir/quast_results"

